### ISSUE TITLE
feature/keep-alive 的切换有些问题，主应用路由与子应用互相切换，地址栏闪烁下跳转失败，报错

### ISSUE THREAD

**Issue by king0817** [gongshun/qiankun-vue-demo#34]
vue-router.esm.js?8c4f:2314 ChunkLoadError: Loading chunk about failed.
(missing: http://localhost:1111/js/about.js)
    at Function.requireEnsure [as e] (http://localhost:1111/js/app.js:906:26)
    at Function.fn.e (http://localhost:1111/js/app.js:187:40)
    at component (webpack-internal:///./src/router/index.js:29:32)
    at eval (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2145:17)
    at eval (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2172:66)
    at Array.map (<anonymous>)
    at eval (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2172:38)
    at Array.map (<anonymous>)
    at flatMapComponents (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2171:26)
    at eval (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2107:5)

**Comment by gongshun** [comment]
兼容 qiankun 旧版本 bug 的代码导致，去掉就可以了

https://github.com/gongshun/qiankun-vue-demo/commit/56690f733c5ca9b6e841bd4451b2c4f9cd3d6954
